<h2>ホーム</h2>
<table class="table table-hover">
	<thead>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>body</th>
			<th>created</th>
			<th>modified</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($rows as $row) : ?>
		<tr>
			<?php foreach ($row as $val) : ?>
			<td><?php echo htmlspecialchars($val) ?></td>
			<?php endforeach ?>
			<td>
					<?php echo $this->tag->linkTo(array("entries/view/{$row->id}", 'View', 'class'=>'btn btn-primary')) ?>
					<?php echo $this->tag->linkTo(array("entries/edit/{$row->id}", 'Edit', 'class'=>'btn btn-primary')) ?>
					<?php echo $this->tag->linkTo(array("entries/delete/{$row->id}", 'Delete', 'class'=>'btn btn-warning', 'onclick'=>'return confirmDelete()')) ?>
			</td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>